# Generated by Django 4.1.1 on 2022-09-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_ordered_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default=None, max_length=255, verbose_name='total'),
        ),
    ]
