# Generated by Django 4.1.1 on 2022-09-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='work_address',
        ),
    ]
