# Generated by Django 4.1.1 on 2022-09-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_address_id_alter_category_id_alter_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='id',
            new_name='uid',
        ),
    ]
