# Generated by Django 4.1.1 on 2022-09-12 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_rename_id_address_uid_rename_id_category_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='uid',
            new_name='id',
        ),
    ]
