# Generated by Django 4.1.1 on 2022-09-12 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_rename_uid_address_id_rename_uid_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='category',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='city',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='item',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='order',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='product',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='town',
            name='ud',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='town',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
